spring:

  redis:
    host: ${secrets.TICKETS_REDIS_HOST}
    port: 6379
    password: ${secrets.TICKETS_REDIS_PW}

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${secrets.TICKETS_DB_URL}
    username: ${secrets.TICKETS_DB_USER}
    password: ${secrets.TICKETS_DB_PW}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${secrets.TICKETS_GMAIL}
    password: ${secrets.TICKETS_GMAIL_PW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        globally_quoted_identifiers: false
        order_by:
          default_null_ordering: last
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

cloud:
  aws:
    s3:
      bucket: tickets2323
    credentials:
      access-key: ${secrets.TICKETS_S3_ACCESS}
      secret-key: ${secrets.TICKETS_S3_SECRET}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    project.backend: debug

jwt:
  secret: ${secrets.TICKETS_SECRET}
  kakao:
    client_id: ${secrets.TICKETS_CLIENT}

server:
  port: 8080
