name: CD with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: "adopt"

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Docker build & push to docker repo
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/ticats .
          docker push ${{ secrets.DOCKER_USERNAME }}/ticats

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker stop ticats || true
            sudo docker rm ticats || true
            sudo docker image rm ${{ secrets.DOCKER_USERNAME }}/ticats:latest || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/ticats:latest
            sudo docker run -d -p 8080:8080 --name ticats ${{ secrets.DOCKER_ENV }} ${{ secrets.DOCKER_USERNAME }}/ticats:latest
